services:
  db:
    image: postgres:14-alpine  # Cambiado de 13-alpine a 14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/appdb
      - DJANGO_SETTINGS_MODULE=gestion_academica.settings
      - ALLOWED_HOSTS=symmetrical-engine-7v7wqqxq5wjp3pxpv-8000.app.github.dev,backend,localhost
    restart: unless-stopped  # Esto ayuda a reiniciar automáticamente
    networks:
      - app-network
    expose:
      - "8000"

  frontend:
    environment:
      - REACT_APP_DOCKER=true
      - REACT_APP_CODESPACES=${CODESPACES:-false}
      - REACT_APP_BACKEND_URL=https://symmetrical-engine-7v7wqqxq5wjp3pxpv-8000.app.github.dev
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
    

volumes:
  postgres_data: